version: '3.8'
services:
  spring-app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-new:3306/test-bvk
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  mysql:
    image: mysql:8
    container_name: mysql-new
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test-bvk
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    external: true

volumes:
  mysql-data:
